components:
    schemas:
        Company:
            # @review
            properties:
                active:
                    readOnly: true
                    type: boolean
                companyId:
                    format: int64
                    type: integer
                domain:
                    description:
                        domain used for email authentication.
                    type: string
                virtualhost:
                    type: string
                webId:
                    type: string
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.headless.admin.taxonomy.client', and version '2.0.1'."
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    title: Liferay Portal Instances Headless API
    version: v1.0
openapi: 3.0.1
paths:
    /companies:
        get:
            description:
                Retrieves the companies
            operationId: getCompaniesPage
            parameters:
              - name: active
                in: query
                required: false
                style: form
                explode: true
                schema:
                  type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Company"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Company"
                                type: array
                    description:
                        default response
            # @review
            tags: ["Company"]
        post:
            description:
                Adds a new company
            operationId: postCompany
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Company"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Company"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Company"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Company"
                    description:
                        default response
            # @review
            tags: ["Company"]
    /companies/{webId}:
        delete:
            description:
                Removes a company
            operationId: deleteCompany
            parameters:
                - in: path
                  name: webId
                  required: true
                  schema:
                      type: string
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
                    description:
                        ""
            # @review
            tags: ["Company"]    
        get:
            description:
                Retrieves the company
            operationId: getCompany
            parameters:
                - in: path
                  name: webId
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Company"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Company"
                    description:
                        default response
            # @review
            tags: ["Company"]
        patch:
            # @review
            description:
                Updates the comany with information sent in the request body. Only the provided fields
                are updated.
            operationId: patchCompany
            parameters:
                - in: path
                  name: webId
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Company"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Company"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Company"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Company"
                    # @review
                    description:
                        "Company successfully updated"
            # @review
            tags: ["Company"]            
    /companies/{webId}/activate:
        # @review
        put:
            description:
                Activates the company
            operationId: putCompanyActivate
            parameters:
                - in: path
                  name: webId
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json: {}
                        application/xml: {}
                    description:
                        default response
            tags: ["Company"]
    /companies/{webId}/deactivate:
        # @review
        put:
            description:
                Deactivates the company. When a company is deactivated, its virtual host will not longer
                respond requests.
            operationId: putCompanyDeactivate
            parameters:
                - in: path
                  name: webId
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json: {}
                        application/xml: {}
                    description:
                        default response
            tags: ["Company"]
